// Generated by lsc from language.verify.ts

datatype StaticType = IntType | BoolType | IntListType | BoolListType

datatype IntList = IntNil | IntCons(head: int, tail: IntList)

datatype BoolList = BoolNil | BoolCons(head: bool, tail: BoolList)

datatype RuntimeValue = IntValue(intValue: int) | BoolValue(boolValue: bool) | IntListValue(intListValue: IntList) | BoolListValue(boolListValue: BoolList)

datatype BindingType = UnboundType | BoundType(bindingType: StaticType)

datatype BindingValue = UnboundValue | BoundValue(bindingValue: RuntimeValue)

datatype Expr = Input | Item | Accumulator | IntLiteral(intValue: int) | BoolLiteral(boolValue: bool) | EmptyIntList | EmptyBoolList | PrependInt(head: Expr, tail: Expr) | PrependBool(head: Expr, tail: Expr) | Add(left: Expr, right: Expr) | Subtract(left: Expr, right: Expr) | Multiply(left: Expr, right: Expr) | LessThan(left: Expr, right: Expr) | EqualInt(left: Expr, right: Expr) | Not(operand: Expr) | And(left: Expr, right: Expr) | IfThenElse(condition: Expr, thenExpr: Expr, elseExpr: Expr)

datatype Program = ExpressionProgram(body: Expr) | MapProgram(mapper: Expr) | FoldRightProgram(initial: Expr, reducer: Expr)

datatype TypeResult = TypeOk(inferred: StaticType) | TypeError

datatype EvalResult = EvalOk(output: RuntimeValue) | EvalError

datatype Example = Example(input: RuntimeValue, output: RuntimeValue)

function typeOk(inferred: StaticType): TypeResult
{
  TypeOk(inferred)
}

function typeError(): TypeResult
{
  TypeResult.TypeError
}

function unboundType(): BindingType
{
  BindingType.UnboundType
}

function boundType(bindingType: StaticType): BindingType
{
  BoundType(bindingType)
}

function unboundValue(): BindingValue
{
  BindingValue.UnboundValue
}

function boundValue(bindingValue: RuntimeValue): BindingValue
{
  BoundValue(bindingValue)
}

function intValue(intValue: int): RuntimeValue
{
  IntValue(intValue)
}

function boolValue(boolValue: bool): RuntimeValue
{
  BoolValue(boolValue)
}

function intNil(): IntList
{
  IntList.IntNil
}

function intCons(head: int, tail: IntList): IntList
{
  IntCons(head, tail)
}

function boolNil(): BoolList
{
  BoolList.BoolNil
}

function boolCons(head: bool, tail: BoolList): BoolList
{
  BoolCons(head, tail)
}

function intListValue(listValue: IntList): RuntimeValue
{
  IntListValue(listValue)
}

function boolListValue(listValue: BoolList): RuntimeValue
{
  BoolListValue(listValue)
}

function evalOk(output: RuntimeValue): EvalResult
{
  EvalOk(output)
}

function evalError(): EvalResult
{
  EvalResult.EvalError
}

function valueType(value: RuntimeValue): StaticType
{
  match value {
    case IntValue(i_value_intValue) =>
      StaticType.IntType
    case BoolValue(i_value_boolValue) =>
      StaticType.BoolType
    case IntListValue(i_value_intListValue) =>
      StaticType.IntListType
    case BoolListValue(i_value_boolListValue) =>
      StaticType.BoolListType
  }
}

function valueMatchesType(value: RuntimeValue, expected: StaticType): bool
{
  if expected.IntType? then
    value.IntValue?
  else
    if expected.BoolType? then
      value.BoolValue?
    else
      if expected.IntListType? then
        value.IntListValue?
      else
        value.BoolListValue?
}

function bindingMatchesType(value: BindingValue, expected: BindingType): bool
{
  match expected {
    case UnboundType =>
      value.UnboundValue?
    case BoundType(i_expected_bindingType) =>
      match value {
        case UnboundValue =>
          false
        case BoundValue(i_value_bindingValue) =>
          valueMatchesType(i_value_bindingValue, i_expected_bindingType)
      }
  }
}

function sameIntList(left: IntList, right: IntList): bool
{
  match left {
    case IntNil =>
      right.IntNil?
    case IntCons(i_left_head, i_left_tail) =>
      ((right.IntCons? && (i_left_head == right.head)) && sameIntList(i_left_tail, right.tail))
  }
}

function sameBoolList(left: BoolList, right: BoolList): bool
{
  match left {
    case BoolNil =>
      right.BoolNil?
    case BoolCons(i_left_head, i_left_tail) =>
      ((right.BoolCons? && (i_left_head == right.head)) && sameBoolList(i_left_tail, right.tail))
  }
}

function sameValue(left: RuntimeValue, right: RuntimeValue): bool
{
  match left {
    case IntValue(i_left_intValue) =>
      (right.IntValue? && (i_left_intValue == right.intValue))
    case BoolValue(i_left_boolValue) =>
      (right.BoolValue? && (i_left_boolValue == right.boolValue))
    case IntListValue(i_left_intListValue) =>
      (right.IntListValue? && sameIntList(i_left_intListValue, right.intListValue))
    case BoolListValue(i_left_boolListValue) =>
      (right.BoolListValue? && sameBoolList(i_left_boolListValue, right.boolListValue))
  }
}

function inferExpression(expr: Expr, inputType: StaticType, itemType: BindingType, accumulatorType: BindingType): TypeResult
{
  match expr {
    case Input =>
      typeOk(inputType)
    case Item =>
      match itemType {
        case BoundType(i_itemType_bindingType) =>
          typeOk(i_itemType_bindingType)
        case UnboundType =>
          typeError()
      }
    case Accumulator =>
      match accumulatorType {
        case BoundType(i_accumulatorType_bindingType) =>
          typeOk(i_accumulatorType_bindingType)
        case UnboundType =>
          typeError()
      }
    case IntLiteral(i_expr_intValue) =>
      typeOk(StaticType.IntType)
    case BoolLiteral(i_expr_boolValue) =>
      typeOk(StaticType.BoolType)
    case EmptyIntList =>
      typeOk(StaticType.IntListType)
    case EmptyBoolList =>
      typeOk(StaticType.BoolListType)
    case _ =>
      if ((((expr.Add? || expr.Subtract?) || expr.Multiply?) || expr.LessThan?) || expr.EqualInt?) then
        var left := inferExpression(expr.left, inputType, itemType, accumulatorType);
        var right := inferExpression(expr.right, inputType, itemType, accumulatorType);
        if (((left.TypeOk? && left.inferred.IntType?) && right.TypeOk?) && right.inferred.IntType?) then
          if ((expr.Add? || expr.Subtract?) || expr.Multiply?) then
            typeOk(StaticType.IntType)
          else
            typeOk(StaticType.BoolType)
        else
          typeError()
      else
        match expr {
          case Not(i_expr_operand) =>
            var operand := inferExpression(i_expr_operand, inputType, itemType, accumulatorType);
            if (operand.TypeOk? && operand.inferred.BoolType?) then
              typeOk(StaticType.BoolType)
            else
              typeError()
          case And(i_expr_left, i_expr_right) =>
            var left := inferExpression(i_expr_left, inputType, itemType, accumulatorType);
            var right := inferExpression(i_expr_right, inputType, itemType, accumulatorType);
            if (((left.TypeOk? && left.inferred.BoolType?) && right.TypeOk?) && right.inferred.BoolType?) then
              typeOk(StaticType.BoolType)
            else
              typeError()
          case PrependInt(i_expr_head, i_expr_tail) =>
            var head := inferExpression(i_expr_head, inputType, itemType, accumulatorType);
            var tail := inferExpression(i_expr_tail, inputType, itemType, accumulatorType);
            if (((head.TypeOk? && head.inferred.IntType?) && tail.TypeOk?) && tail.inferred.IntListType?) then
              typeOk(StaticType.IntListType)
            else
              typeError()
          case PrependBool(i_expr_head, i_expr_tail) =>
            var head := inferExpression(i_expr_head, inputType, itemType, accumulatorType);
            var tail := inferExpression(i_expr_tail, inputType, itemType, accumulatorType);
            if (((head.TypeOk? && head.inferred.BoolType?) && tail.TypeOk?) && tail.inferred.BoolListType?) then
              typeOk(StaticType.BoolListType)
            else
              typeError()
          case _ =>
            var condition := inferExpression(expr.condition, inputType, itemType, accumulatorType);
            var thenType := inferExpression(expr.thenExpr, inputType, itemType, accumulatorType);
            var elseType := inferExpression(expr.elseExpr, inputType, itemType, accumulatorType);
            if ((((condition.TypeOk? && condition.inferred.BoolType?) && thenType.TypeOk?) && elseType.TypeOk?) && (thenType.inferred == elseType.inferred)) then
              typeOk(thenType.inferred)
            else
              typeError()
        }
  }
}

function evaluateExpression(expr: Expr, input: RuntimeValue, item: BindingValue, accumulator: BindingValue): EvalResult
{
  match expr {
    case Input =>
      evalOk(input)
    case Item =>
      match item {
        case BoundValue(i_item_bindingValue) =>
          evalOk(i_item_bindingValue)
        case UnboundValue =>
          evalError()
      }
    case Accumulator =>
      match accumulator {
        case BoundValue(i_accumulator_bindingValue) =>
          evalOk(i_accumulator_bindingValue)
        case UnboundValue =>
          evalError()
      }
    case IntLiteral(i_expr_intValue) =>
      evalOk(intValue(i_expr_intValue))
    case BoolLiteral(i_expr_boolValue) =>
      evalOk(boolValue(i_expr_boolValue))
    case EmptyIntList =>
      evalOk(intListValue(intNil()))
    case EmptyBoolList =>
      evalOk(boolListValue(boolNil()))
    case _ =>
      if ((((expr.Add? || expr.Subtract?) || expr.Multiply?) || expr.LessThan?) || expr.EqualInt?) then
        var left := evaluateExpression(expr.left, input, item, accumulator);
        var right := evaluateExpression(expr.right, input, item, accumulator);
        if (((left.EvalOk? && left.output.IntValue?) && right.EvalOk?) && right.output.IntValue?) then
          match expr {
            case Add(i_expr_left, i_expr_right) =>
              evalOk(intValue((left.output.intValue + right.output.intValue)))
            case Subtract(i_expr_left, i_expr_right) =>
              evalOk(intValue((left.output.intValue - right.output.intValue)))
            case Multiply(i_expr_left, i_expr_right) =>
              evalOk(intValue((left.output.intValue * right.output.intValue)))
            case LessThan(i_expr_left, i_expr_right) =>
              evalOk(boolValue((left.output.intValue < right.output.intValue)))
            case _ =>
              evalOk(boolValue((left.output.intValue == right.output.intValue)))
          }
        else
          evalError()
      else
        match expr {
          case Not(i_expr_operand) =>
            var operand := evaluateExpression(i_expr_operand, input, item, accumulator);
            if (operand.EvalOk? && operand.output.BoolValue?) then
              evalOk(boolValue(!(operand.output.boolValue)))
            else
              evalError()
          case And(i_expr_left, i_expr_right) =>
            var left := evaluateExpression(i_expr_left, input, item, accumulator);
            var right := evaluateExpression(i_expr_right, input, item, accumulator);
            if (((left.EvalOk? && left.output.BoolValue?) && right.EvalOk?) && right.output.BoolValue?) then
              evalOk(boolValue((left.output.boolValue && right.output.boolValue)))
            else
              evalError()
          case PrependInt(i_expr_head, i_expr_tail) =>
            var head := evaluateExpression(i_expr_head, input, item, accumulator);
            var tail := evaluateExpression(i_expr_tail, input, item, accumulator);
            if (((head.EvalOk? && head.output.IntValue?) && tail.EvalOk?) && tail.output.IntListValue?) then
              evalOk(intListValue(intCons(head.output.intValue, tail.output.intListValue)))
            else
              evalError()
          case PrependBool(i_expr_head, i_expr_tail) =>
            var head := evaluateExpression(i_expr_head, input, item, accumulator);
            var tail := evaluateExpression(i_expr_tail, input, item, accumulator);
            if (((head.EvalOk? && head.output.BoolValue?) && tail.EvalOk?) && tail.output.BoolListValue?) then
              evalOk(boolListValue(boolCons(head.output.boolValue, tail.output.boolListValue)))
            else
              evalError()
          case _ =>
            var condition := evaluateExpression(expr.condition, input, item, accumulator);
            if ((!condition.EvalOk?) || (!condition.output.BoolValue?)) then
              evalError()
            else
              if condition.output.boolValue then
                evaluateExpression(expr.thenExpr, input, item, accumulator)
              else
                evaluateExpression(expr.elseExpr, input, item, accumulator)
        }
  }
}

function listItemType(inputType: StaticType): TypeResult
{
  if inputType.IntListType? then
    typeOk(StaticType.IntType)
  else
    if inputType.BoolListType? then
      typeOk(StaticType.BoolType)
    else
      typeError()
}

function listTypeForScalar(scalarType: StaticType): TypeResult
{
  if scalarType.IntType? then
    typeOk(StaticType.IntListType)
  else
    if scalarType.BoolType? then
      typeOk(StaticType.BoolListType)
    else
      typeError()
}

function expressionUsesInput(expr: Expr): bool
{
  match expr {
    case Input =>
      true
    case _ =>
      if (((((expr.Item? || expr.Accumulator?) || expr.IntLiteral?) || expr.BoolLiteral?) || expr.EmptyIntList?) || expr.EmptyBoolList?) then
        false
      else
        match expr {
          case Not(i_expr_operand) =>
            expressionUsesInput(i_expr_operand)
          case IfThenElse(i_expr_condition, i_expr_thenExpr, i_expr_elseExpr) =>
            ((expressionUsesInput(i_expr_condition) || expressionUsesInput(i_expr_thenExpr)) || expressionUsesInput(i_expr_elseExpr))
          case _ =>
            if (expr.PrependInt? || expr.PrependBool?) then
              (expressionUsesInput(expr.head) || expressionUsesInput(expr.tail))
            else
              (expressionUsesInput(expr.left) || expressionUsesInput(expr.right))
        }
  }
}

function inferType(program: Program, inputType: StaticType): TypeResult
{
  match program {
    case MapProgram(i_program_mapper) =>
      if expressionUsesInput(i_program_mapper) then
        typeError()
      else
        var itemType := listItemType(inputType);
        match itemType {
          case TypeError =>
            typeError()
          case TypeOk(i_itemType_inferred) =>
            var mapperType := inferExpression(i_program_mapper, inputType, boundType(i_itemType_inferred), unboundType());
            match mapperType {
              case TypeError =>
                typeError()
              case TypeOk(i_mapperType_inferred) =>
                listTypeForScalar(i_mapperType_inferred)
            }
        }
    case FoldRightProgram(i_program_initial, i_program_reducer) =>
      if (expressionUsesInput(i_program_initial) || expressionUsesInput(i_program_reducer)) then
        typeError()
      else
        var itemType := listItemType(inputType);
        match itemType {
          case TypeError =>
            typeError()
          case TypeOk(i_itemType_inferred) =>
            var initialType := inferExpression(i_program_initial, inputType, unboundType(), unboundType());
            match initialType {
              case TypeError =>
                typeError()
              case TypeOk(i_initialType_inferred) =>
                var reducerType := inferExpression(i_program_reducer, inputType, boundType(i_itemType_inferred), boundType(i_initialType_inferred));
                if (reducerType.TypeOk? && (reducerType.inferred == i_initialType_inferred)) then
                  typeOk(i_initialType_inferred)
                else
                  typeError()
            }
        }
    case ExpressionProgram(i_program_body) =>
      inferExpression(i_program_body, inputType, unboundType(), unboundType())
  }
}

function evaluateMapInt(mapper: Expr, originalInput: RuntimeValue, list: IntList, mapperType: StaticType): EvalResult
  decreases list
{
  match list {
    case IntNil =>
      if mapperType.IntType? then
        evalOk(intListValue(intNil()))
      else
        if mapperType.BoolType? then
          evalOk(boolListValue(boolNil()))
        else
          evalError()
    case IntCons(i_list_head, i_list_tail) =>
      var mappedHead := evaluateExpression(mapper, originalInput, boundValue(intValue(i_list_head)), unboundValue());
      match mappedHead {
        case EvalError =>
          evalError()
        case EvalOk(i_mappedHead_output) =>
          var mappedTail := evaluateMapInt(mapper, originalInput, i_list_tail, mapperType);
          match mappedTail {
            case EvalError =>
              evalError()
            case EvalOk(i_mappedTail_output) =>
              if ((mapperType.IntType? && i_mappedHead_output.IntValue?) && i_mappedTail_output.IntListValue?) then
                evalOk(intListValue(intCons(i_mappedHead_output.intValue, i_mappedTail_output.intListValue)))
              else
                if ((mapperType.BoolType? && i_mappedHead_output.BoolValue?) && i_mappedTail_output.BoolListValue?) then
                  evalOk(boolListValue(boolCons(i_mappedHead_output.boolValue, i_mappedTail_output.boolListValue)))
                else
                  evalError()
          }
      }
  }
}

function evaluateMapBool(mapper: Expr, originalInput: RuntimeValue, list: BoolList, mapperType: StaticType): EvalResult
  decreases list
{
  match list {
    case BoolNil =>
      if mapperType.IntType? then
        evalOk(intListValue(intNil()))
      else
        if mapperType.BoolType? then
          evalOk(boolListValue(boolNil()))
        else
          evalError()
    case BoolCons(i_list_head, i_list_tail) =>
      var mappedHead := evaluateExpression(mapper, originalInput, boundValue(boolValue(i_list_head)), unboundValue());
      match mappedHead {
        case EvalError =>
          evalError()
        case EvalOk(i_mappedHead_output) =>
          var mappedTail := evaluateMapBool(mapper, originalInput, i_list_tail, mapperType);
          match mappedTail {
            case EvalError =>
              evalError()
            case EvalOk(i_mappedTail_output) =>
              if ((mapperType.IntType? && i_mappedHead_output.IntValue?) && i_mappedTail_output.IntListValue?) then
                evalOk(intListValue(intCons(i_mappedHead_output.intValue, i_mappedTail_output.intListValue)))
              else
                if ((mapperType.BoolType? && i_mappedHead_output.BoolValue?) && i_mappedTail_output.BoolListValue?) then
                  evalOk(boolListValue(boolCons(i_mappedHead_output.boolValue, i_mappedTail_output.boolListValue)))
                else
                  evalError()
          }
      }
  }
}

function evaluateFoldRightInt(reducer: Expr, originalInput: RuntimeValue, list: IntList, initial: RuntimeValue): EvalResult
  decreases list
{
  match list {
    case IntNil =>
      evalOk(initial)
    case IntCons(i_list_head, i_list_tail) =>
      var foldedTail := evaluateFoldRightInt(reducer, originalInput, i_list_tail, initial);
      match foldedTail {
        case EvalError =>
          evalError()
        case EvalOk(i_foldedTail_output) =>
          evaluateExpression(reducer, originalInput, boundValue(intValue(i_list_head)), boundValue(i_foldedTail_output))
      }
  }
}

function evaluateFoldRightBool(reducer: Expr, originalInput: RuntimeValue, list: BoolList, initial: RuntimeValue): EvalResult
  decreases list
{
  match list {
    case BoolNil =>
      evalOk(initial)
    case BoolCons(i_list_head, i_list_tail) =>
      var foldedTail := evaluateFoldRightBool(reducer, originalInput, i_list_tail, initial);
      match foldedTail {
        case EvalError =>
          evalError()
        case EvalOk(i_foldedTail_output) =>
          evaluateExpression(reducer, originalInput, boundValue(boolValue(i_list_head)), boundValue(i_foldedTail_output))
      }
  }
}

function evaluate(program: Program, input: RuntimeValue): EvalResult
{
  match program {
    case MapProgram(i_program_mapper) =>
      var inputType := valueType(input);
      var itemType := listItemType(inputType);
      match itemType {
        case TypeError =>
          evalError()
        case TypeOk(i_itemType_inferred) =>
          var mapperType := inferExpression(i_program_mapper, inputType, boundType(i_itemType_inferred), unboundType());
          match mapperType {
            case TypeError =>
              evalError()
            case TypeOk(i_mapperType_inferred) =>
              match input {
                case IntListValue(i_input_intListValue) =>
                  evaluateMapInt(i_program_mapper, input, i_input_intListValue, i_mapperType_inferred)
                case BoolListValue(i_input_boolListValue) =>
                  evaluateMapBool(i_program_mapper, input, i_input_boolListValue, i_mapperType_inferred)
                case _ =>
                  evalError()
              }
          }
      }
    case FoldRightProgram(i_program_initial, i_program_reducer) =>
      var initial := evaluateExpression(i_program_initial, input, unboundValue(), unboundValue());
      match initial {
        case EvalError =>
          evalError()
        case EvalOk(i_initial_output) =>
          match input {
            case IntListValue(i_input_intListValue) =>
              evaluateFoldRightInt(i_program_reducer, input, i_input_intListValue, i_initial_output)
            case BoolListValue(i_input_boolListValue) =>
              evaluateFoldRightBool(i_program_reducer, input, i_input_boolListValue, i_initial_output)
            case _ =>
              evalError()
          }
      }
    case ExpressionProgram(i_program_body) =>
      evaluateExpression(i_program_body, input, unboundValue(), unboundValue())
  }
}

function expressionBodyCost(expr: Expr): int
  ensures expressionBodyCost(expr) >= 1
{
  if ((((((expr.Input? || expr.Item?) || expr.Accumulator?) || expr.IntLiteral?) || expr.BoolLiteral?) || expr.EmptyIntList?) || expr.EmptyBoolList?) then
    1
  else
    match expr {
      case Not(i_expr_operand) =>
        (1 + expressionBodyCost(i_expr_operand))
      case IfThenElse(i_expr_condition, i_expr_thenExpr, i_expr_elseExpr) =>
        (((1 + expressionBodyCost(i_expr_condition)) + expressionBodyCost(i_expr_thenExpr)) + expressionBodyCost(i_expr_elseExpr))
      case _ =>
        if (expr.PrependInt? || expr.PrependBool?) then
          ((1 + expressionBodyCost(expr.head)) + expressionBodyCost(expr.tail))
        else
          ((1 + expressionBodyCost(expr.left)) + expressionBodyCost(expr.right))
    }
}

lemma expressionBodyCost_ensures(expr: Expr)
  ensures (expressionBodyCost(expr) >= 1)
{
}

function expressionCost(program: Program): int
{
  match program {
    case MapProgram(i_program_mapper) =>
      (2 + expressionBodyCost(i_program_mapper))
    case FoldRightProgram(i_program_initial, i_program_reducer) =>
      ((3 + expressionBodyCost(i_program_initial)) + expressionBodyCost(i_program_reducer))
    case ExpressionProgram(i_program_body) =>
      expressionBodyCost(i_program_body)
  }
}

lemma expressionCost_ensures(program: Program)
  ensures (expressionCost(program) >= 1)
{
}

function matchesExample(program: Program, example: Example): bool
{
  var result := evaluate(program, example.input);
  match result {
    case EvalError =>
      false
    case EvalOk(i_result_output) =>
      sameValue(i_result_output, example.output)
  }
}

function examplesMatchSignatureFrom(examples: seq<Example>, index: int, inputType: StaticType, outputType: StaticType): bool
  requires (index >= 0)
  decreases (|examples| - index)
{
  ((index >= |examples|) || (var example := examples[index]; (if ((valueType(example.input) != inputType) || (valueType(example.output) != outputType)) then false else examplesMatchSignatureFrom(examples, (index + 1), inputType, outputType))))
}

function examplesHaveSignature(examples: seq<Example>): bool
{
  if (|examples| == 0) then
    false
  else
    examplesMatchSignatureFrom(examples, 1, valueType(examples[0].input), valueType(examples[0].output))
}

lemma examplesHaveSignature_ensures(examples: seq<Example>)
  ensures ((examplesHaveSignature(examples) == true) ==> (|examples| > 0))
{
}

function matchesAllExamplesFrom(program: Program, examples: seq<Example>, index: int): bool
  requires (index >= 0)
  decreases (|examples| - index)
{
  ((index >= |examples|) || (if !(matchesExample(program, examples[index])) then false else matchesAllExamplesFrom(program, examples, (index + 1))))
}

function matchesAllExamples(program: Program, examples: seq<Example>): bool
{
  matchesAllExamplesFrom(program, examples, 0)
}

function acceptProgram(program: Program, examples: seq<Example>): bool
{
  if (|examples| == 0) then
    false
  else
    if !(examplesHaveSignature(examples)) then
      false
    else
      var inferred := inferType(program, valueType(examples[0].input));
      match inferred {
        case TypeError =>
          false
        case TypeOk(i_inferred_inferred) =>
          if (i_inferred_inferred != valueType(examples[0].output)) then
            false
          else
            matchesAllExamples(program, examples)
      }
}

lemma acceptProgram_ensures(program: Program, examples: seq<Example>)
  ensures ((acceptProgram(program, examples) == true) ==> (|examples| > 0))
{
}

// Additions below this line are maintained by hand. The generated prefix above
// is refreshed from language.verify.ts by `lsc regen`.

lemma {:timeLimit 60} {:isolate_assertions} EvaluateExpressionSound(
  expr: Expr,
  input: RuntimeValue,
  inputType: StaticType,
  item: BindingValue,
  itemType: BindingType,
  accumulator: BindingValue,
  accumulatorType: BindingType
)
  requires valueMatchesType(input, inputType)
  requires bindingMatchesType(item, itemType)
  requires bindingMatchesType(accumulator, accumulatorType)
  requires inferExpression(expr, inputType, itemType, accumulatorType).TypeOk?
  ensures evaluateExpression(expr, input, item, accumulator).EvalOk?
  ensures valueMatchesType(
    evaluateExpression(expr, input, item, accumulator).output,
    inferExpression(expr, inputType, itemType, accumulatorType).inferred
  )
  decreases expr
{
  match expr {
    case Input =>
    case Item =>
    case Accumulator =>
    case IntLiteral(_) =>
    case BoolLiteral(_) =>
    case EmptyIntList =>
    case EmptyBoolList =>
    case PrependInt(head, tail) =>
      EvaluateExpressionSound(
        head, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        tail, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case PrependBool(head, tail) =>
      EvaluateExpressionSound(
        head, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        tail, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case Add(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case Subtract(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case Multiply(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case LessThan(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case EqualInt(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case Not(operand) =>
      EvaluateExpressionSound(
        operand, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case And(left, right) =>
      EvaluateExpressionSound(
        left, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        right, input, inputType, item, itemType, accumulator, accumulatorType
      );
    case IfThenElse(condition, thenExpr, elseExpr) =>
      EvaluateExpressionSound(
        condition, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        thenExpr, input, inputType, item, itemType, accumulator, accumulatorType
      );
      EvaluateExpressionSound(
        elseExpr, input, inputType, item, itemType, accumulator, accumulatorType
      );
  }
}

lemma EvaluateMapIntSound(
  mapper: Expr,
  originalInput: RuntimeValue,
  list: IntList,
  mapperType: StaticType
)
  requires originalInput.IntListValue?
  requires mapperType.IntType? || mapperType.BoolType?
  requires inferExpression(
    mapper,
    StaticType.IntListType,
    BoundType(StaticType.IntType),
    BindingType.UnboundType
  ).TypeOk?
  requires inferExpression(
    mapper,
    StaticType.IntListType,
    BoundType(StaticType.IntType),
    BindingType.UnboundType
  ).inferred == mapperType
  ensures evaluateMapInt(mapper, originalInput, list, mapperType).EvalOk?
  ensures mapperType.IntType? ==>
    evaluateMapInt(mapper, originalInput, list, mapperType).output.IntListValue?
  ensures mapperType.BoolType? ==>
    evaluateMapInt(mapper, originalInput, list, mapperType).output.BoolListValue?
  decreases list
{
  match list {
    case IntNil =>
    case IntCons(head, tail) =>
      EvaluateExpressionSound(
        mapper,
        originalInput,
        StaticType.IntListType,
        BoundValue(IntValue(head)),
        BoundType(StaticType.IntType),
        BindingValue.UnboundValue,
        BindingType.UnboundType
      );
      EvaluateMapIntSound(mapper, originalInput, tail, mapperType);
  }
}

lemma EvaluateMapBoolSound(
  mapper: Expr,
  originalInput: RuntimeValue,
  list: BoolList,
  mapperType: StaticType
)
  requires originalInput.BoolListValue?
  requires mapperType.IntType? || mapperType.BoolType?
  requires inferExpression(
    mapper,
    StaticType.BoolListType,
    BoundType(StaticType.BoolType),
    BindingType.UnboundType
  ).TypeOk?
  requires inferExpression(
    mapper,
    StaticType.BoolListType,
    BoundType(StaticType.BoolType),
    BindingType.UnboundType
  ).inferred == mapperType
  ensures evaluateMapBool(mapper, originalInput, list, mapperType).EvalOk?
  ensures mapperType.IntType? ==>
    evaluateMapBool(mapper, originalInput, list, mapperType).output.IntListValue?
  ensures mapperType.BoolType? ==>
    evaluateMapBool(mapper, originalInput, list, mapperType).output.BoolListValue?
  decreases list
{
  match list {
    case BoolNil =>
    case BoolCons(head, tail) =>
      EvaluateExpressionSound(
        mapper,
        originalInput,
        StaticType.BoolListType,
        BoundValue(BoolValue(head)),
        BoundType(StaticType.BoolType),
        BindingValue.UnboundValue,
        BindingType.UnboundType
      );
      EvaluateMapBoolSound(mapper, originalInput, tail, mapperType);
  }
}

lemma EvaluateFoldRightIntSound(
  reducer: Expr,
  originalInput: RuntimeValue,
  list: IntList,
  initial: RuntimeValue,
  accumulatorType: StaticType
)
  requires originalInput.IntListValue?
  requires valueMatchesType(initial, accumulatorType)
  requires inferExpression(
    reducer,
    StaticType.IntListType,
    BoundType(StaticType.IntType),
    BoundType(accumulatorType)
  ).TypeOk?
  requires inferExpression(
    reducer,
    StaticType.IntListType,
    BoundType(StaticType.IntType),
    BoundType(accumulatorType)
  ).inferred == accumulatorType
  ensures evaluateFoldRightInt(reducer, originalInput, list, initial).EvalOk?
  ensures valueMatchesType(
    evaluateFoldRightInt(reducer, originalInput, list, initial).output,
    accumulatorType
  )
  decreases list
{
  match list {
    case IntNil =>
    case IntCons(head, tail) =>
      EvaluateFoldRightIntSound(
        reducer, originalInput, tail, initial, accumulatorType
      );
      EvaluateExpressionSound(
        reducer,
        originalInput,
        StaticType.IntListType,
        BoundValue(IntValue(head)),
        BoundType(StaticType.IntType),
        BoundValue(evaluateFoldRightInt(
          reducer, originalInput, tail, initial
        ).output),
        BoundType(accumulatorType)
      );
  }
}

lemma EvaluateFoldRightBoolSound(
  reducer: Expr,
  originalInput: RuntimeValue,
  list: BoolList,
  initial: RuntimeValue,
  accumulatorType: StaticType
)
  requires originalInput.BoolListValue?
  requires valueMatchesType(initial, accumulatorType)
  requires inferExpression(
    reducer,
    StaticType.BoolListType,
    BoundType(StaticType.BoolType),
    BoundType(accumulatorType)
  ).TypeOk?
  requires inferExpression(
    reducer,
    StaticType.BoolListType,
    BoundType(StaticType.BoolType),
    BoundType(accumulatorType)
  ).inferred == accumulatorType
  ensures evaluateFoldRightBool(reducer, originalInput, list, initial).EvalOk?
  ensures valueMatchesType(
    evaluateFoldRightBool(reducer, originalInput, list, initial).output,
    accumulatorType
  )
  decreases list
{
  match list {
    case BoolNil =>
    case BoolCons(head, tail) =>
      EvaluateFoldRightBoolSound(
        reducer, originalInput, tail, initial, accumulatorType
      );
      EvaluateExpressionSound(
        reducer,
        originalInput,
        StaticType.BoolListType,
        BoundValue(BoolValue(head)),
        BoundType(StaticType.BoolType),
        BoundValue(evaluateFoldRightBool(
          reducer, originalInput, tail, initial
        ).output),
        BoundType(accumulatorType)
      );
  }
}

lemma EvaluateProgramSound(
  program: Program,
  input: RuntimeValue,
  inputType: StaticType
)
  requires valueMatchesType(input, inputType)
  requires inferType(program, inputType).TypeOk?
  ensures evaluate(program, input).EvalOk?
  ensures valueMatchesType(
    evaluate(program, input).output,
    inferType(program, inputType).inferred
  )
{
  match program {
    case ExpressionProgram(body) =>
      EvaluateExpressionSound(
        body,
        input,
        inputType,
        BindingValue.UnboundValue,
        BindingType.UnboundType,
        BindingValue.UnboundValue,
        BindingType.UnboundType
      );
    case MapProgram(mapper) =>
      if inputType.IntListType? {
        EvaluateMapIntSound(
          mapper,
          input,
          input.intListValue,
          inferExpression(
            mapper,
            inputType,
            BoundType(StaticType.IntType),
            BindingType.UnboundType
          ).inferred
        );
      } else {
        EvaluateMapBoolSound(
          mapper,
          input,
          input.boolListValue,
          inferExpression(
            mapper,
            inputType,
            BoundType(StaticType.BoolType),
            BindingType.UnboundType
          ).inferred
        );
      }
    case FoldRightProgram(initial, reducer) =>
      EvaluateExpressionSound(
        initial,
        input,
        inputType,
        BindingValue.UnboundValue,
        BindingType.UnboundType,
        BindingValue.UnboundValue,
        BindingType.UnboundType
      );
      if inputType.IntListType? {
        EvaluateFoldRightIntSound(
          reducer,
          input,
          input.intListValue,
          evaluateExpression(
            initial,
            input,
            BindingValue.UnboundValue,
            BindingValue.UnboundValue
          ).output,
          inferExpression(
            initial,
            inputType,
            BindingType.UnboundType,
            BindingType.UnboundType
          ).inferred
        );
      } else {
        EvaluateFoldRightBoolSound(
          reducer,
          input,
          input.boolListValue,
          evaluateExpression(
            initial,
            input,
            BindingValue.UnboundValue,
            BindingValue.UnboundValue
          ).output,
          inferExpression(
            initial,
            inputType,
            BindingType.UnboundType,
            BindingType.UnboundType
          ).inferred
        );
      }
  }
}

lemma ExpressionBodyCostExceedsDirectChildren(expr: Expr)
  ensures expr.Not? ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.operand)
  ensures (expr.Add? || expr.Subtract? || expr.Multiply? ||
           expr.LessThan? || expr.EqualInt? || expr.And?) ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.left)
  ensures (expr.Add? || expr.Subtract? || expr.Multiply? ||
           expr.LessThan? || expr.EqualInt? || expr.And?) ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.right)
  ensures (expr.PrependInt? || expr.PrependBool?) ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.head)
  ensures (expr.PrependInt? || expr.PrependBool?) ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.tail)
  ensures expr.IfThenElse? ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.condition)
  ensures expr.IfThenElse? ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.thenExpr)
  ensures expr.IfThenElse? ==>
    expressionBodyCost(expr) > expressionBodyCost(expr.elseExpr)
{
}

lemma ProgramCostExceedsContainedBodies(program: Program)
  ensures program.MapProgram? ==>
    expressionCost(program) > expressionBodyCost(program.mapper)
  ensures program.FoldRightProgram? ==>
    expressionCost(program) > expressionBodyCost(program.initial)
  ensures program.FoldRightProgram? ==>
    expressionCost(program) > expressionBodyCost(program.reducer)
{
}

lemma MatchesExampleExact(program: Program, example: Example)
  ensures matchesExample(program, example) <==>
    (evaluate(program, example.input).EvalOk? &&
     sameValue(evaluate(program, example.input).output, example.output))
{
}

lemma MatchesAllExamplesFromExact(
  program: Program,
  examples: seq<Example>,
  index: int
)
  requires 0 <= index <= |examples|
  ensures matchesAllExamplesFrom(program, examples, index) <==>
    (forall i :: index <= i < |examples| ==>
      matchesExample(program, examples[i]))
  decreases |examples| - index
{
  if index < |examples| {
    MatchesAllExamplesFromExact(program, examples, index + 1);
  }
}

lemma MatchesAllExamplesExact(program: Program, examples: seq<Example>)
  ensures matchesAllExamples(program, examples) <==>
    (forall i :: 0 <= i < |examples| ==>
      matchesExample(program, examples[i]))
{
  MatchesAllExamplesFromExact(program, examples, 0);
}

lemma ExamplesMatchSignatureFromExact(
  examples: seq<Example>,
  index: int,
  inputType: StaticType,
  outputType: StaticType
)
  requires 0 <= index <= |examples|
  ensures examplesMatchSignatureFrom(
    examples, index, inputType, outputType
  ) <==>
    ((forall i :: index <= i < |examples| ==>
        valueType(examples[i].input) == inputType) &&
     (forall i :: index <= i < |examples| ==>
        valueType(examples[i].output) == outputType))
  decreases |examples| - index
{
  if index < |examples| {
    ExamplesMatchSignatureFromExact(
      examples, index + 1, inputType, outputType
    );
  }
}

lemma ExamplesHaveSignatureExact(examples: seq<Example>)
  ensures examplesHaveSignature(examples) <==>
    (|examples| > 0 &&
     (forall i :: 0 <= i < |examples| ==>
        valueType(examples[i].input) == valueType(examples[0].input)) &&
     (forall i :: 0 <= i < |examples| ==>
        valueType(examples[i].output) == valueType(examples[0].output)))
{
  if |examples| > 0 {
    ExamplesMatchSignatureFromExact(
      examples,
      1,
      valueType(examples[0].input),
      valueType(examples[0].output)
    );
  }
}

lemma AcceptProgramExact(program: Program, examples: seq<Example>)
  ensures acceptProgram(program, examples) <==>
    (|examples| > 0 &&
     examplesHaveSignature(examples) &&
     inferType(program, valueType(examples[0].input)).TypeOk? &&
     inferType(program, valueType(examples[0].input)).inferred ==
       valueType(examples[0].output) &&
     (forall i :: 0 <= i < |examples| ==>
        matchesExample(program, examples[i])))
{
  MatchesAllExamplesExact(program, examples);
}

lemma AcceptedProgramSound(program: Program, examples: seq<Example>)
  requires acceptProgram(program, examples)
  ensures |examples| > 0
  ensures examplesHaveSignature(examples)
  ensures inferType(program, valueType(examples[0].input)).TypeOk?
  ensures inferType(program, valueType(examples[0].input)).inferred ==
    valueType(examples[0].output)
  ensures forall i :: 0 <= i < |examples| ==>
    evaluate(program, examples[i].input).EvalOk?
  ensures forall i :: 0 <= i < |examples| ==>
    sameValue(evaluate(program, examples[i].input).output, examples[i].output)
{
  MatchesAllExamplesExact(program, examples);
  forall i | 0 <= i < |examples|
    ensures evaluate(program, examples[i].input).EvalOk?
    ensures sameValue(
      evaluate(program, examples[i].input).output,
      examples[i].output
    )
  {
    MatchesExampleExact(program, examples[i]);
  }
}
