"""Typer command adapter for the synthesis application service."""

from __future__ import annotations

import typer

from modelsmc_pbe.shell.options import (
    AlphaOption,
    ApiKeyEnvOption,
    ArtifactsDirOption,
    BaseUrlOption,
    BetaMaxOption,
    CandidateBatchSizeOption,
    DeductionMixOption,
    DeductionStrengthOption,
    DeviceOption,
    EssThresholdOption,
    FamilyDeductionMixOption,
    GrammarLimitOption,
    HoleDeductionMixOption,
    HoleMaxCostOption,
    HoleStateLimitOption,
    IterationsOption,
    LLMEnergyNormalizationOption,
    MaterializeReferenceOption,
    MaxConcurrencyOption,
    MaxScoredCandidatesOption,
    MaxTokensOption,
    ModelOption,
    ModelRepositoryOption,
    ModelRevisionOption,
    ModeOption,
    MovesPerStageOption,
    ParticlesOption,
    ProposalEpsilonOption,
    ProposalOption,
    ScoreBatchSizeOption,
    ScoreCacheDirOption,
    ScoreCacheModeOption,
    SeedOption,
    SemanticScaleOption,
    SemanticSlateSizeOption,
    SkeletonOption,
    SpecArgument,
    SupportLimitOption,
    TemperatureOption,
    TimeoutSecondsOption,
    TokenizerRevisionOption,
    TraceOption,
    VLLMServerConfigOption,
)
from modelsmc_pbe.shell.request import SynthesizeRequest
from modelsmc_pbe.shell.runner import run_synthesis


def synthesize(
    spec: SpecArgument,
    mode: ModeOption = "paper-search",
    proposal: ProposalOption = "catalog",
    model: ModelOption = "qwen3-coder:30b-a3b-q8_0",
    model_repository: ModelRepositoryOption = None,
    model_revision: ModelRevisionOption = None,
    tokenizer_revision: TokenizerRevisionOption = None,
    vllm_server_config: VLLMServerConfigOption = None,
    base_url: BaseUrlOption = None,
    api_key_env: ApiKeyEnvOption = None,
    score_cache_dir: ScoreCacheDirOption = None,
    score_cache_mode: ScoreCacheModeOption = "off",
    skeleton: SkeletonOption = "auto",
    particles: ParticlesOption = None,
    iterations: IterationsOption = None,
    alpha: AlphaOption = None,
    ess_threshold: EssThresholdOption = None,
    seed: SeedOption = None,
    beta_max: BetaMaxOption = 1.0,
    moves_per_stage: MovesPerStageOption = 1,
    grammar_limit: GrammarLimitOption = 250_000,
    score_batch_size: ScoreBatchSizeOption = 512,
    candidate_batch_size: CandidateBatchSizeOption = 128,
    max_scored_candidates: MaxScoredCandidatesOption = 10_000,
    hole_max_cost: HoleMaxCostOption = 3,
    hole_state_limit: HoleStateLimitOption = 250_000,
    support_limit: SupportLimitOption = 250_000,
    materialize_reference: MaterializeReferenceOption = False,
    proposal_epsilon: ProposalEpsilonOption = 0.05,
    semantic_scale: SemanticScaleOption = 1.0,
    semantic_slate_size: SemanticSlateSizeOption = None,
    deduction_mix: DeductionMixOption = 0.5,
    family_deduction_mix: FamilyDeductionMixOption = None,
    hole_deduction_mix: HoleDeductionMixOption = None,
    deduction_strength: DeductionStrengthOption = 2.0,
    temperature: TemperatureOption = 0.7,
    llm_energy_normalization: LLMEnergyNormalizationOption = "total-full-prompt-logprob",
    max_tokens: MaxTokensOption = 4_096,
    max_concurrency: MaxConcurrencyOption = 8,
    timeout_seconds: TimeoutSecondsOption = 300.0,
    device: DeviceOption = None,
    artifacts_dir: ArtifactsDirOption = None,
    trace: TraceOption = False,
) -> None:
    """Synthesize and score a typed program from input/output examples."""

    request = SynthesizeRequest(
        spec=spec,
        mode=mode,
        proposal=proposal,
        model=model,
        model_repository=model_repository,
        model_revision=model_revision,
        tokenizer_revision=tokenizer_revision,
        vllm_server_config=vllm_server_config,
        base_url=base_url,
        api_key_env=api_key_env,
        score_cache_dir=score_cache_dir,
        score_cache_mode=score_cache_mode,
        skeleton=skeleton,
        particles=particles,
        iterations=iterations,
        alpha=alpha,
        ess_threshold=ess_threshold,
        seed=seed,
        beta_max=beta_max,
        moves_per_stage=moves_per_stage,
        grammar_limit=grammar_limit,
        score_batch_size=score_batch_size,
        candidate_batch_size=candidate_batch_size,
        max_scored_candidates=max_scored_candidates,
        hole_max_cost=hole_max_cost,
        hole_state_limit=hole_state_limit,
        support_limit=support_limit,
        materialize_reference=materialize_reference,
        proposal_epsilon=proposal_epsilon,
        semantic_scale=semantic_scale,
        semantic_slate_size=semantic_slate_size,
        deduction_mix=deduction_mix,
        family_deduction_mix=family_deduction_mix,
        hole_deduction_mix=hole_deduction_mix,
        deduction_strength=deduction_strength,
        temperature=temperature,
        llm_energy_normalization=llm_energy_normalization,
        max_tokens=max_tokens,
        max_concurrency=max_concurrency,
        timeout_seconds=timeout_seconds,
        device=device,
        artifacts_dir=artifacts_dir,
        trace=trace,
    )
    try:
        run_synthesis(request)
    except (OSError, RuntimeError, ValueError) as error:
        typer.secho(f"error: {error}", fg=typer.colors.RED, err=True)
        raise typer.Exit(code=2) from error
