"""Deterministic held-out generation and semantic evaluation.

Held-out inputs are generated by SHA-256 rather than the process-global random
module, making the corpus stable across Python versions and machines.  The
oracle registry is explicit and version-controlled; no expected answer is
inferred from a synthesized program.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import Any, cast

from modelsmc_pbe.core.evaluate import evaluate_program
from modelsmc_pbe.domain.ast import ProgramAst, canonical_key, normalize_program
from research.protocol import TaskSpec, load_protocol

type RuntimeValue = int | bool | list[int] | list[bool]
Oracle = Callable[[RuntimeValue], RuntimeValue]


def _as_int(value: RuntimeValue) -> int:
    if not isinstance(value, int) or isinstance(value, bool):
        raise TypeError("oracle expected Int input")
    return value


def _as_int_list(value: RuntimeValue) -> list[int]:
    if not isinstance(value, list) or any(
        not isinstance(item, int) or isinstance(item, bool) for item in value
    ):
        raise TypeError("oracle expected List<Int> input")
    return cast(list[int], value)


def _affine(value: RuntimeValue) -> RuntimeValue:
    return 2 * _as_int(value) + 1


def _negative(value: RuntimeValue) -> RuntimeValue:
    return _as_int(value) < 0


def _map_increment(value: RuntimeValue) -> RuntimeValue:
    return [item + 1 for item in _as_int_list(value)]


def _list_sum(value: RuntimeValue) -> RuntimeValue:
    return sum(_as_int_list(value))


def _filter_positive(value: RuntimeValue) -> RuntimeValue:
    return [item for item in _as_int_list(value) if item > 0]


def _bounded_square(value: RuntimeValue) -> RuntimeValue:
    return [item * item for item in _as_int_list(value) if -2 < item < 3]


def _signed_window(value: RuntimeValue) -> RuntimeValue:
    return [(-item if item < 0 else item * item) for item in _as_int_list(value) if -3 < item < 3]


def _window_penalty_sum(value: RuntimeValue) -> RuntimeValue:
    def contribution(item: int) -> int:
        if item < -1:
            return 0
        if item < 3:
            return item * item
        return -item

    return sum(contribution(item) for item in _as_int_list(value))


ORACLES: dict[str, Oracle] = {
    "affine_2x_plus_1": _affine,
    "negative_int": _negative,
    "map_increment": _map_increment,
    "list_sum": _list_sum,
    "filter_positive": _filter_positive,
    "bounded_square": _bounded_square,
    "signed_window": _signed_window,
    "window_penalty_sum": _window_penalty_sum,
}


def _normalize_runtime(value: object) -> RuntimeValue:
    if isinstance(value, bool):
        return value
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        try:
            return int(value)
        except ValueError as error:
            raise ValueError(f"runtime string is not an integer: {value!r}") from error
    if isinstance(value, list):
        normalized = [_normalize_runtime(item) for item in value]
        if all(isinstance(item, bool) for item in normalized):
            return cast(list[bool], normalized)
        if all(isinstance(item, int) and not isinstance(item, bool) for item in normalized):
            return cast(list[int], normalized)
    raise ValueError(f"unsupported runtime value: {value!r}")


def _training_inputs(spec_path: Path) -> set[str]:
    document = json.loads(spec_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict) or not isinstance(document.get("examples"), list):
        raise ValueError(f"invalid PBE specification: {spec_path}")
    result: set[str] = set()
    for example in document["examples"]:
        if not isinstance(example, dict) or "input" not in example:
            raise ValueError(f"invalid training example in {spec_path}")
        value = _normalize_runtime(example["input"])
        result.add(_runtime_key(value))
    return result


def _digest_int(*parts: object) -> int:
    payload = "\x1f".join(str(part) for part in parts).encode()
    return int.from_bytes(hashlib.sha256(payload).digest()[:8], "big")


def _runtime_key(value: RuntimeValue) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def _verify_corpus(task: TaskSpec, values: tuple[RuntimeValue, ...]) -> tuple[RuntimeValue, ...]:
    content = json.dumps(values, separators=(",", ":"), ensure_ascii=False).encode()
    actual = hashlib.sha256(content).hexdigest()
    expected = task.heldout.corpus_sha256
    if actual != expected:
        raise ValueError(
            f"held-out corpus drift for {task.task_id}: expected {expected}, received {actual}"
        )
    return values


def generate_inputs(task: TaskSpec) -> tuple[RuntimeValue, ...]:
    """Generate the task's frozen held-out inputs, excluding training inputs."""

    heldout = task.heldout
    excluded = _training_inputs(task.spec_path)
    if heldout.max_length is None:
        available: list[RuntimeValue] = [
            value
            for value in range(heldout.minimum, heldout.maximum + 1)
            if _runtime_key(value) not in excluded
        ]
        available.sort(
            key=lambda value: (_digest_int(heldout.seed, task.task_id, value), cast(int, value))
        )
        if len(available) < heldout.count:
            raise ValueError(
                f"task {task.task_id} requests {heldout.count} held-out scalars but only "
                f"{len(available)} are available"
            )
        return _verify_corpus(task, tuple(available[: heldout.count]))

    width = heldout.maximum - heldout.minimum + 1
    selected: list[RuntimeValue] = []
    seen = set(excluded)
    counter = 0
    maximum_attempts = max(10_000, heldout.count * 1_000)
    while len(selected) < heldout.count and counter < maximum_attempts:
        length = _digest_int(heldout.seed, task.task_id, counter, "length") % (
            heldout.max_length + 1
        )
        candidate = [
            heldout.minimum
            + _digest_int(heldout.seed, task.task_id, counter, position) % width
            for position in range(length)
        ]
        key = _runtime_key(candidate)
        if key not in seen:
            seen.add(key)
            selected.append(candidate)
        counter += 1
    if len(selected) != heldout.count:
        raise ValueError(f"could not generate {heldout.count} unique cases for {task.task_id}")
    return _verify_corpus(task, tuple(selected))


def generate_cases(task: TaskSpec) -> tuple[tuple[RuntimeValue, RuntimeValue], ...]:
    """Return immutable input/expected pairs for one declared oracle."""

    try:
        oracle = ORACLES[task.heldout.oracle]
    except KeyError as error:
        raise ValueError(f"unknown held-out oracle {task.heldout.oracle!r}") from error
    return tuple((value, oracle(value)) for value in generate_inputs(task))


def _same_runtime(left: object, right: object) -> bool:
    if isinstance(left, bool) or isinstance(right, bool):
        return isinstance(left, bool) and isinstance(right, bool) and left == right
    if isinstance(left, int) or isinstance(right, int):
        return (
            isinstance(left, int)
            and not isinstance(left, bool)
            and isinstance(right, int)
            and not isinstance(right, bool)
            and left == right
        )
    if isinstance(left, list) and isinstance(right, list):
        return len(left) == len(right) and all(
            _same_runtime(a, b) for a, b in zip(left, right, strict=True)
        )
    return False


def _extract_program_with_source(
    result_document: object,
) -> tuple[ProgramAst, str] | None:
    """Extract the declared discovery champion and its artifact field.

    New lazy-search artifacts persist ``best_visited`` across the entire run.
    Older artifacts predate that contract, so ``sampled_best`` and ``champion``
    remain explicit legacy fallbacks only when ``best_visited`` is absent.
    """

    if not isinstance(result_document, dict) or result_document.get("status") != "completed":
        return None
    result = result_document.get("result")
    if not isinstance(result, dict):
        return None

    source: str
    candidate: object
    if "best_visited" in result:
        best_visited = result.get("best_visited")
        if not isinstance(best_visited, dict):
            return None
        candidate = best_visited.get("program")
        source = "best_visited"
    else:
        sampled_best = result.get("sampled_best")
        champion = result.get("champion")
        if isinstance(sampled_best, dict):
            candidate = sampled_best.get("program")
            source = "sampled_best_legacy_fallback"
        elif isinstance(champion, dict):
            candidate = champion.get("program")
            source = "champion_legacy_fallback"
        else:
            return None
    if candidate is None:
        return None
    try:
        return normalize_program(candidate), source
    except ValueError:
        return None


def extract_program(result_document: object) -> ProgramAst | None:
    """Extract the program selected for held-out evaluation."""

    extracted = _extract_program_with_source(result_document)
    return None if extracted is None else extracted[0]


def unavailable_evaluation(task: TaskSpec, reason: str) -> dict[str, Any]:
    """Return a stable negative held-out record for an intention-to-treat failure."""

    return {
        "schema_version": 1,
        "task_id": task.task_id,
        "oracle": task.heldout.oracle,
        "heldout_seed": task.heldout.seed,
        "status": "unavailable",
        "reason": reason,
        "cases": task.heldout.count,
        "passed": 0,
        "accuracy": 0.0,
        "exact": False,
        "program_sha256": None,
        "program_source": None,
        "evaluations": [],
    }


def evaluate_result(task: TaskSpec, result_path: Path) -> dict[str, Any]:
    """Evaluate the archived champion against the task's frozen held-out set."""

    if not result_path.is_file():
        return unavailable_evaluation(task, "result.json is missing")
    try:
        document = json.loads(result_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return unavailable_evaluation(task, f"result.json is unreadable: {error}")
    extracted = _extract_program_with_source(document)
    if extracted is None:
        return unavailable_evaluation(task, "completed champion AST is unavailable")
    program, program_source = extracted

    evaluations: list[dict[str, Any]] = []
    passed = 0
    for index, (input_value, expected) in enumerate(generate_cases(task), start=1):
        predicted = evaluate_program(program, input_value)
        exact = _same_runtime(predicted, expected)
        passed += int(exact)
        evaluations.append(
            {
                "case": index,
                "input": input_value,
                "expected": expected,
                "predicted": predicted,
                "exact": exact,
            }
        )
    count = len(evaluations)
    return {
        "schema_version": 1,
        "task_id": task.task_id,
        "oracle": task.heldout.oracle,
        "heldout_seed": task.heldout.seed,
        "status": "completed",
        "reason": None,
        "cases": count,
        "passed": passed,
        "accuracy": passed / count,
        "exact": passed == count,
        "program_sha256": hashlib.sha256(canonical_key(program).encode()).hexdigest(),
        "program_source": program_source,
        "evaluations": evaluations,
    }


def write_json_atomic(path: Path, document: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    with temporary.open("w", encoding="utf-8") as stream:
        json.dump(document, stream, indent=2, sort_keys=True, ensure_ascii=False, allow_nan=False)
        stream.write("\n")
        stream.flush()
        os.fsync(stream.fileno())
    temporary.replace(path)


def _task(protocol_path: Path, task_id: str) -> TaskSpec:
    protocol = load_protocol(protocol_path)
    try:
        return next(task for task in protocol.tasks if task.task_id == task_id)
    except StopIteration as error:
        raise ValueError(f"unknown task {task_id!r}") from error


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--protocol", type=Path, default=Path(__file__).with_name("protocol.json"))
    parser.add_argument("--task", required=True)
    parser.add_argument("--result", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    task = _task(args.protocol, args.task)
    evaluation = evaluate_result(task, args.result.expanduser().resolve())
    write_json_atomic(args.output.expanduser().resolve(), evaluation)
    print(json.dumps({key: evaluation[key] for key in ("status", "cases", "passed", "exact")}))
    return 0 if evaluation["status"] == "completed" else 2


if __name__ == "__main__":
    raise SystemExit(main())
